# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X1t1rRqsTfqxSC3HWythjuJ2sWfS0dvf
"""

import streamlit as st
import requests
from streamlit_lottie import st_lottie
import joblib
import numpy as np

st.set_page_config(page_title='Company Loan Eligibility', page_icon='::star::')

def load_lottie(url): # test url if you want to use your own lottie file 'valid url' or 'invalid url'
    r = requests.get(url)
    if r.status_code != 200:
        return None
    return r.json()

def prepare_input_data_for_model(_RATE_owner_1,_RATE_owner_2,_location , _RATE_ID_FOR_years_in_business,_RATE_ID_FOR_location,_RATE_ID_FOR_num_negative_days,_RATE_ID_FOR_tax_lien_count,_RATE_ID_FOR_current_position,_INPUT_VALUE_ID_FOR_industry_type,_RATE_owner_4,_RATE_ID_FOR_judgement_lien_percent,_RATE_ID_FOR_judgement_lien_amount,_RATE_ID_FOR_num_deposits,_RATE_ID_FOR_monthly_gross,_RATE_ID_FOR_average_ledger,_RATE_ID_FOR_fc_margin,_RATE_ID_FOR_tax_lien_amount,_RATE_ID_FOR_tax_lien_percent,_funded_last_30):

    if _RATE_owner_1 == 'A':
        RATE_owner_1 = 0
    elif _RATE_owner_1 == 'B':
        RATE_owner_1 = 1
    elif _RATE_owner_1 == 'C':
        RATE_owner_1 = 2
    elif _RATE_owner_1 == 'D':
        RATE_owner_1 = 3
    elif _RATE_owner_1 == 'R':
        RATE_owner_1 = 4
    else:
         RATE_owner_1 = 5

    #---------------------------------
    if _RATE_owner_2 == 'A':
        RATE_owner_2 = 0
    elif _RATE_owner_2 == 'B':
        RATE_owner_2 = 1
    elif _RATE_owner_2 == 'C':
        RATE_owner_2 = 2
    elif _RATE_owner_2 == 'D':
        RATE_owner_2 = 3
    elif _RATE_owner_2 == 'R':
        RATE_owner_2 = 4
    else:
         RATE_owner_2 = 5
    #---------------------------------
    if _RATE_owner_4 == 'A':
        RATE_owner_4 = 0
    elif _RATE_owner_4 == 'B':
        RATE_owner_4 = 1
    elif _RATE_owner_4 == 'C':
        RATE_owner_4 = 2
    elif _RATE_owner_4 == 'D':
        RATE_owner_4= 3
    elif _RATE_owner_4 == 'R':
        RATE_owner_4 = 4
    else:
         RATE_owner_4 = 5
    #---------------------------------
    if _location == 'BRICK':
        location = 0
    elif _location == 'Home':
        location = 1
    elif _location == 'Unknown':
        location = 2
    elif _location == 'Verified':
        location = 3
    else:
         location = 4
    #---------------------------------
    if _INPUT_VALUE_ID_FOR_industry_type == 'Preferred':
        INPUT_VALUE_ID_FOR_industry_type = 0
    elif _INPUT_VALUE_ID_FOR_industry_type == 'capped':
        INPUT_VALUE_ID_FOR_industry_type = 1
    elif _INPUT_VALUE_ID_FOR_industry_type == 'preferred':
        INPUT_VALUE_ID_FOR_industry_type = 2
    elif _INPUT_VALUE_ID_FOR_industry_type == 'standard':
        INPUT_VALUE_ID_FOR_industry_type = 3
    else:
         INPUT_VALUE_ID_FOR_industry_type = 4
    #---------------------------------
    if _funded_last_30 == 'Yes':
        funded_last_30 = 1
    else:
        funded_last_30 = 0
    #---------------------------------
    if  _RATE_ID_FOR_years_in_business == 'A':
        RATE_ID_FOR_years_in_business = 0
    elif _RATE_ID_FOR_years_in_business == 'B':
        RATE_ID_FOR_years_in_business = 1
    elif _RATE_ID_FOR_years_in_business == 'C':
        RATE_ID_FOR_years_in_business = 2
    elif _RATE_ID_FOR_years_in_business == 'D':
        RATE_ID_FOR_years_in_business = 3
    elif _RATE_ID_FOR_years_in_business == 'R':
        RATE_owner_1 = 4
    else:
         RATE_ID_FOR_years_in_business = 5
    #---------------------------------
    if  _RATE_ID_FOR_location == 'A':
        RATE_ID_FOR_location = 0
    elif _RATE_ID_FOR_location == 'B':
        RATE_ID_FOR_location = 1
    elif _RATE_ID_FOR_location == 'C':
        RATE_ID_FOR_location = 2
    elif _RATE_ID_FOR_location == 'D':
        RATE_ID_FOR_location = 3
    elif _RATE_ID_FOR_location == 'R':
        RATE_ID_FOR_location = 4
    else:
         RATE_ID_FOR_location = 5
    #---------------------------------
    if  _RATE_ID_FOR_num_negative_days == 'A':
        RATE_ID_FOR_num_negative_days = 0
    elif _RATE_ID_FOR_num_negative_days == 'B':
        RATE_ID_FOR_location = 1
    elif _RATE_ID_FOR_num_negative_days == 'C':
        RATE_ID_FOR_num_negative_days = 2
    elif _RATE_ID_FOR_num_negative_days == 'D':
        RATE_ID_FOR_num_negative_days = 3
    elif _RATE_ID_FOR_num_negative_days == 'R':
        RATE_ID_FOR_num_negative_days = 4
    else:
         RATE_ID_FOR_num_negative_days = 5
    #---------------------------------
    if  _RATE_ID_FOR_tax_lien_count == 'A':
        RATE_ID_FOR_tax_lien_count = 0
    elif _RATE_ID_FOR_tax_lien_count == 'B':
        RATE_ID_FOR_tax_lien_count = 1
    elif _RATE_ID_FOR_tax_lien_count == 'C':
        RATE_ID_FOR_tax_lien_count = 2
    elif _RATE_ID_FOR_tax_lien_count == 'D':
        RATE_ID_FOR_tax_lien_count = 3
    elif _RATE_ID_FOR_tax_lien_count == 'R':
        RATE_ID_FOR_tax_lien_count = 4
    else:
         RATE_ID_FOR_tax_lien_count = 5
    #---------------------------------
    if  _RATE_ID_FOR_current_position == 'A':
        RATE_ID_FOR_current_position = 0
    elif _RATE_ID_FOR_current_position == 'B':
        RATE_ID_FOR_current_position = 1
    elif _RATE_ID_FOR_current_position == 'C':
        RATE_ID_FOR_current_position = 2
    elif _RATE_ID_FOR_current_position == 'D':
        RATE_ID_FOR_current_position = 3
    elif _RATE_ID_FOR_current_position == 'R':
        RATE_ID_FOR_current_position = 4
    else:
         RATE_ID_FOR_current_position = 5
    #---------------------------------
    if  _RATE_ID_FOR_judgement_lien_percent == 'A':
        RATE_ID_FOR_judgement_lien_percent = 0
    elif _RATE_ID_FOR_judgement_lien_percent == 'B':
        RATE_ID_FOR_judgement_lien_percent = 1
    elif _RATE_ID_FOR_judgement_lien_percent == 'C':
        RATE_ID_FOR_judgement_lien_percent = 2
    elif _RATE_ID_FOR_judgement_lien_percent == 'D':
        RATE_ID_FOR_judgement_lien_percent = 3
    elif _RATE_ID_FOR_judgement_lien_percent == 'R':
        RATE_ID_FOR_judgement_lien_percent = 4
    else:
         RATE_ID_FOR_judgement_lien_percent = 5
    #---------------------------------
    if  _RATE_ID_FOR_judgement_lien_amount == 'A':
        RATE_ID_FOR_judgement_lien_amount = 0
    elif _RATE_ID_FOR_judgement_lien_amount == 'B':
        RATE_ID_FOR_judgement_lien_amount = 1
    elif _RATE_ID_FOR_judgement_lien_amount == 'C':
        RATE_ID_FOR_judgement_lien_amount = 2
    elif _RATE_ID_FOR_judgement_lien_amount == 'D':
        RATE_ID_FOR_judgement_lien_amount = 3
    elif _RATE_ID_FOR_judgement_lien_amount == 'R':
        RATE_ID_FOR_judgement_lien_amount = 4
    else:
         RATE_ID_FOR_judgement_lien_amount = 5
    #---------------------------------
    if  _RATE_ID_FOR_judgement_lien_amount == 'A':
        RATE_ID_FOR_judgement_lien_amount = 0
    elif _RATE_ID_FOR_judgement_lien_amount == 'B':
        RATE_ID_FOR_judgement_lien_amount = 1
    elif _RATE_ID_FOR_judgement_lien_amount == 'C':
        RATE_ID_FOR_judgement_lien_amount = 2
    elif _RATE_ID_FOR_judgement_lien_amount == 'D':
        RATE_ID_FOR_judgement_lien_amount = 3
    elif _RATE_ID_FOR_judgement_lien_amount == 'R':
        RATE_ID_FOR_judgement_lien_amount = 4
    else:
         RATE_ID_FOR_judgement_lien_amount = 5
    #---------------------------------
    if  _RATE_ID_FOR_num_deposits == 'A':
        RATE_ID_FOR_num_deposits = 0
    elif _RATE_ID_FOR_num_deposits == 'B':
        RATE_ID_FOR_num_deposits = 1
    elif _RATE_ID_FOR_num_deposits == 'C':
        RATE_ID_FOR_num_deposits = 2
    elif _RATE_ID_FOR_num_deposits == 'D':
        RATE_ID_FOR_num_deposits = 3
    elif _RATE_ID_FOR_num_deposits == 'R':
        RATE_ID_FOR_num_deposits = 4
    else:
         RATE_ID_FOR_num_deposits = 5
   #---------------------------------
    if  _RATE_ID_FOR_monthly_gross == 'A':
        RATE_ID_FOR_monthly_gross = 0
    elif _RATE_ID_FOR_monthly_gross == 'B':
        RATE_ID_FOR_monthly_gross = 1
    elif _RATE_ID_FOR_monthly_gross == 'C':
        RATE_ID_FOR_monthly_gross = 2
    elif _RATE_ID_FOR_monthly_gross == 'D':
        RATE_ID_FOR_monthly_gross = 3
    elif _RATE_ID_FOR_monthly_gross == 'R':
        RATE_ID_FOR_monthly_gross = 4
    else:
         RATE_ID_FOR_monthly_gross = 5
    #---------------------------------
    if  _RATE_ID_FOR_average_ledger == 'A':
        RATE_ID_FOR_average_ledger = 0
    elif _RATE_ID_FOR_average_ledger == 'B':
        RATE_ID_FOR_average_ledger = 1
    elif _RATE_ID_FOR_average_ledger == 'C':
        RATE_ID_FOR_average_ledger = 2
    elif _RATE_ID_FOR_average_ledger == 'D':
        RATE_ID_FOR_average_ledger = 3
    elif _RATE_ID_FOR_average_ledger == 'R':
        RATE_ID_FOR_average_ledger = 4
    else:
         RATE_ID_FOR_average_ledger = 5
    #---------------------------------
    if  _RATE_ID_FOR_fc_margin == 'A':
        RATE_ID_FOR_fc_margin = 0
    elif _RATE_ID_FOR_fc_margin == 'B':
        RATE_ID_FOR_fc_margin = 1
    elif _RATE_ID_FOR_fc_margin == 'C':
        RATE_ID_FOR_fc_margin = 2
    elif _RATE_ID_FOR_fc_margin == 'D':
        RATE_ID_FOR_fc_margin = 3
    elif _RATE_ID_FOR_fc_margin == 'R':
        RATE_ID_FOR_fc_margin = 4
    else:
         RATE_ID_FOR_fc_margin = 5
    #---------------------------------
    if  _RATE_ID_FOR_tax_lien_amount == 'A':
        RATE_ID_FOR_tax_lien_amount = 0
    elif _RATE_ID_FOR_tax_lien_amount == 'B':
        RATE_ID_FOR_tax_lien_amount = 1
    elif _RATE_ID_FOR_tax_lien_amount == 'C':
        RATE_ID_FOR_tax_lien_amount = 2
    elif _RATE_ID_FOR_tax_lien_amount == 'D':
        RATE_ID_FOR_tax_lien_amount = 3
    elif _RATE_ID_FOR_tax_lien_amount == 'R':
        RATE_ID_FOR_tax_lien_amount = 4
    else:
         RATE_ID_FOR_tax_lien_amount = 5
    #---------------------------------
    if  _RATE_ID_FOR_tax_lien_percent == 'A':
        RATE_ID_FOR_tax_lien_percent = 0
    elif _RATE_ID_FOR_tax_lien_percent == 'B':
        RATE_ID_FOR_tax_lien_percent = 1
    elif _RATE_ID_FOR_tax_lien_percent == 'C':
        RATE_ID_FOR_tax_lien_percent = 2
    elif _RATE_ID_FOR_tax_lien_percent == 'D':
        RATE_ID_FOR_tax_lien_percent = 3
    elif _RATE_ID_FOR_tax_lien_percent == 'R':
        RATE_ID_FOR_tax_lien_percent = 4
    else:
         RATE_ID_FOR_tax_lien_percent = 5


    A = [RATE_owner_1,RATE_owner_2,location,RATE_ID_FOR_years_in_business,RATE_ID_FOR_location,RATE_ID_FOR_num_negative_days,RATE_ID_FOR_tax_lien_count,RATE_ID_FOR_current_position,INPUT_VALUE_ID_FOR_industry_type,RATE_owner_4,RATE_ID_FOR_judgement_lien_percent,RATE_ID_FOR_judgement_lien_amount,RATE_ID_FOR_num_deposits,RATE_ID_FOR_monthly_gross,RATE_ID_FOR_average_ledger,RATE_ID_FOR_fc_margin,RATE_ID_FOR_tax_lien_amount,RATE_ID_FOR_tax_lien_percent,funded_last_30]
    sample = np.array(A).reshape(-1,len(A))

    return sample



loaded_model = joblib.load(open("Company_loan_model", 'rb'))



st.write('# Company Loan Eligibility ')
#st.header('Placement')

lottie_link = "https://lottie.host/6994bc3f-4f36-4ab6-9f44-4646cea87690/oVQQrhTlNb.json"
animation = load_lottie(lottie_link)

st.write('---')
st.subheader('Enter your details to predict if your company is eligible for a loan')

with st.container():

    right_column, left_column = st.columns(2)

    with right_column:
        owner_1_score= st.number_input('Owner 1 credit score:', min_value=0.0, max_value=10000, value=0.0, step=0.1)
        RATE_owner_1 = st.radio('The interest rate assigned to the loan based on the credit score of the first owner: ', ['A', 'B','C','D','R'])
        CAP_AMOUNT_owner_1 = st.number_input('The maximum loan amount that can be approved based on the creditworthiness of the first owner:', min_value=0.0, max_value=150000, value=0.0, step=0.1)
        PERCENT_OWN_owner_1 = st.number_input('The percentage ownership of the first owner in the company:', min_value=0.0, max_value=100.0, value=0.0, step=0.1)
        #-------------------------------------------------------------------------------------------------------------------------------------
        owner_2_score= st.number_input('Owner 2 credit score:', min_value=0.0, max_value=10000, value=0.0, step=0.1)
        RATE_owner_2 = st.radio('The interest rate assigned to the loan based on the credit score of the second owner: ', ['A', 'B','C','D','R'])
        CAP_AMOUNT_owner_2 = st.number_input('The maximum loan amount that can be approved based on the creditworthiness of the second owner:', min_value=0.0, max_value=150000, value=0.0, step=0.1)
        PERCENT_OWN_owner_2 = st.number_input('The percentage ownership of the second owner in the company:')
        #-------------------------------------------------------------------------------------------------------------------------------------
        INPUT_VALUE_owner_4= st.number_input('Owner 4 credit score:', min_value=0.0, max_value=10000, value=0.0, step=0.1)
        RATE_owner_4 = st.radio('The interest rate assigned to the loan based on the credit score of the fourth owner: ', ['A', 'B','C','D','R'])
        CAP_AMOUNT_owner_4 = st.number_input('The maximum loan amount that can be approved based on the creditworthiness of the fourth owner:', min_value=0.0, max_value=150000, value=0.0, step=0.1)
        PERCENT_OWN_owner_4 = st.number_input('The percentage ownership of the fourth owner in the company:', min_value=0.0, max_value=100.0, value=0.0, step=0.1)
        #-------------------------------------------------------------------------------------------------------------------------------------
        years_in_business = st.number_input('The number of years the company has been in operation:', min_value=0.0, max_value=100.0, value=0.0, step=0.1)
        RATE_ID_FOR_years_in_business = st.radio('Interest rate based on the number of years in business: ', ['A', 'B','C','D','R'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        fsr = st.number_input('Financial Stability Rating:', min_value=0.0, max_value=100.0, value=0.0, step=0.1)
        #-------------------------------------------------------------------------------------------------------------------------------------
        location = st.radio('The geographical location of the company: ', ['Home', 'Verified','Unknown','BRICK'])
        RATE_ID_FOR_location = st.radio('Interest rate based on the company\'s location: ', ['A', 'B','C','D','R'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        funded_last_30 = st.radio('has the company been funded in the last 30 days?: ', ['Yes','No'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        judgement_lien_percent = st.number_input('The percentage of the company\'s assets affected by judgment liens:', min_value=0.0, max_value=100.0, value=0.0, step=0.1)
        RATE_ID_FOR_judgement_lien_percent= st.radio('Interest rate variation due to judgment lien percentage: ', ['A', 'B','C','D','R'])
        INPUT_VALUE_ID_FOR_judgement_lien_amount = st.number_input('Input value for judgment lien amount:', min_value=0.0, max_value=1000000, value=0.0, step=0.1)
        RATE_ID_FOR_judgement_lien_amount = st.radio('Interest rate adjustment based on judgment lien amount',['A', 'B','C','D','R'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        INPUT_VALUE_ID_FOR_num_negative_days = st.number_input('Input value representing the number of negative balance days:', min_value=0.0, max_value=3000, value=0.0, step=0.1)
        RATE_ID_FOR_num_negative_days = st.radio('Interest rate adjustment based on the number of negative balance days:',['A', 'B','C','D','R'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        INPUT_VALUE_ID_FOR_num_deposits = st.number_input('Input value indicating the number of deposits made:', min_value=0.0, max_value=500, value=0.0, step=0.1)
        RATE_ID_FOR_num_deposits = ('Interest rate adjustment based on the number of deposits:',['A', 'B','C','D','R'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        INPUT_VALUE_ID_FOR_monthly_gross = st.number_input('Input value for the monthly gross income of the company:', min_value=0.0, max_value=3000000, value=0.0, step=0.1)
        RATE_ID_FOR_monthly_gross = ('Interest rate adjustment based on the monthly gross income:',['A', 'B','C','D','R'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        INPUT_VALUE_ID_FOR_average_ledger = st.number_input('Input value for the average ledger balance:', min_value=0.0, max_value=600000, value=0.0, step=0.1)
        RATE_ID_FOR_average_ledger = ('Interest rate adjustment based on the average ledger balance:',['A', 'B','C','D','R'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        INPUT_VALUE_ID_FOR_fc_margin = st.number_input('Input value for the financial center margin:', min_value=0.0, max_value=3, value=0.0, step=0.1)
        RATE_ID_FOR_fc_margin = ('Interest rate adjustment based on the financial center margin:',['A', 'B','C','D','R'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        INPUT_VALUE_ID_FOR_tax_lien_amount = st.number_input('Input value for the total tax lien amount:', min_value=0.0, max_value=900000, value=0.0, step=0.1)
        RATE_ID_FOR_tax_lien_amount = ('Interest rate adjustment based on the total tax lien amount:',['A', 'B','C','D','R'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        INPUT_VALUE_ID_FOR_tax_lien_percent = st.number_input('Input value for the percentage of assets affected by tax liens:', min_value=0.0, max_value=100, value=0.0, step=0.1)
        RATE_ID_FOR_tax_lien_percent = ('Interest rate adjustment based on the tax lien percentage:',['A', 'B','C','D','R'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        INPUT_VALUE_ID_FOR_tax_lien_count = st.number_input('Input value for the count of tax liens:', min_value=0.0, max_value=10, value=0.0, step=0.1)
        RATE_ID_FOR_tax_lien_count = ('Interest rate adjustment based on the count of tax liens:',['A', 'B','C','D','R'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        INPUT_VALUE_ID_FOR_current_position = st.number_input('Input value representing the current position of the company:', min_value=0.0, max_value=10, value=0.0, step=0.1)
        RATE_ID_FOR_current_position = ('Interest rate adjustment based on the current position:',['A', 'B','C','D','R'])
        #-------------------------------------------------------------------------------------------------------------------------------------
        INPUT_VALUE_ID_FOR_avg_net_deposits = st.number_input('Input value for the average net deposits:', min_value=0.0, max_value=3000000, value=0.0, step=0.1)
        #-------------------------------------------------------------------------------------------------------------------------------------
        INPUT_VALUE_ID_FOR_industry_type = ('Input value representing the industry type of the company:',['preferred','capped','standard','Preferred'])

        sample = prepare_input_data_for_model(RATE_owner_1,RATE_owner_2,location,RATE_ID_FOR_years_in_business,RATE_ID_FOR_location,RATE_ID_FOR_num_negative_days,RATE_ID_FOR_tax_lien_count,RATE_ID_FOR_current_position,INPUT_VALUE_ID_FOR_industry_type,RATE_owner_4,RATE_ID_FOR_judgement_lien_percent,RATE_ID_FOR_judgement_lien_amount,RATE_ID_FOR_num_deposits,RATE_ID_FOR_monthly_gross,RATE_ID_FOR_average_ledger,RATE_ID_FOR_fc_margin,RATE_ID_FOR_tax_lien_amount,RATE_ID_FOR_tax_lien_percent,funded_last_30)


    with left_column:
        st_lottie(animation, speed=1, height=400, key="initial")


    if st.button('Predict'):
            pred_Y = loaded_model.predict(sample)

            if pred_Y == 0:
                #st.write("## Predicted Status : ", result)
                st.write('### Congratulations!! You are eligible.')
                st.balloons()
            else:
                st.write('### Sorry!! You are not eligible.')